### ISSUE TITLE
use transparent favicon

### ISSUE THREAD

**Issue by v01d** [apache/incubator-nuttx-website#29]
When building the documentation with Sphinx I made the background of the favicon transparent as it looks better.
You can find it at: https://nuttx.apache.org/docs/latest/_static/favicon.ico (or on the nuttx repo of course).

**Comment by btashton** [comment]
Can you also update the favicon.ico reference to something like `favicon.ico?v=1` browsers heavily cache these settings. We can also put this off, but just be aware most people won't see the change for a long time.

**Comment by v01d** [comment]
You mean on sphinx? Or on the website?
